### ISSUE TITLE
V1.3 power error (grey screen of death)

### ISSUE THREAD

**Issue by ATerribleModder1** [Dubwise56/MarsX#39]
after building a power device at random the screen will turn gray. deleting the affected object/objects in dev mode will cause the game too freak out and i cant deconstruct anything as well as spamming the log with a million more errors. 

here is the dev mode log 
https://pastebin.com/1vAZ2i0w

this error happens on both vanilla marsx (no other mods than core) and modded marsx (quality of life mods + marsx and core)
i did verify rimworlds game files incase this was too do with the game however the issue persisted. 

the really odd thing is that previously unaffected save files of the same colony with start having grey screens to. 

![20220104123711_1](https://user-images.githubusercontent.com/41817987/148002277-b5b46fb5-3ca9-4735-b0dc-4536ddffafdb.jpg)

**Comment by Dubwise56** [comment]
i think its because an eva suit was dropped onto some power conduit, fixing now

**Comment by Dubwise56** [comment]
should be fixed in new release
